version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 4
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major-updates:
        patterns:
          - "*"
        update-types:
          - major

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
